### ISSUE TITLE
Add a Kinto plugin that would keep an up-to-date collections with the list of products, versions and locales

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#103]
Compute 3 collections from the releases collection that would provide a way to grab the filters using the elm-kinto client.

That would be another pick at using ES for the demo.

**Comment by magopian** [comment]
The idea would be to have a collection for each of the filters, and update them on each new (or updated) build record.

The list of filter (and thus collections) we need are:
- products
- versions
- platforms
- channels
- locales

Each collection should have one record for each "filter value". Another option would be to have one "filters" collection, and 5 records (each records consisting of a list of filter values).

**Comment by n1k0** [comment]
I'm gonna take care of using these new collections.

**Comment by Natim** [comment]
I have initiated the collection with the index_filters script.

- https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/version_filters/records
- https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/locale_filters/records
- https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/platform_filters/records
- https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/channel_filters/records
- https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/product_filters/records
