### ISSUE TITLE
Add build permalinks

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/buildhub#108]
We should add permalinks for builds, so user can easily share information about a single build.

Previous issue content for the records:

>1. go to https://mozilla-services.github.io/buildhub/#/builds/product/firefox/channel/beta/platform/all/version/54.0b13/locale/en-US
>2. click the second entry permalink (https://mozilla-services.github.io/buildhub/#firefox_beta_54-0b13_linux->x86_64_en-us)
>3. fennec builds are listed, they shouldn't as we want a builds

**Comment by magopian** [comment]
The first link is a "filtered list" (that you can get to by submitting the filter form). The second one is a "direct link" using a plain standard anchor. Which used to work when we had the whole list of builds: it would then just scroll you to the anchor (the specific entry).

In your case, the second link actually displays the full unfiltered list, but only the first page (so only the first 10 results), and then tries to scroll to the anchor (which isn't even displayed on the page).

This isn't relevant anymore, and I believe we should simply remove the link... or build a new one with all the info we can have about this build (product, channel, platform, version, locale, and build id if it's present).

**Comment by Natim** [comment]
> I believe we should simply build a new link with all the info we can have about this build (product, channel, platform, version, locale)

👍 

Note that the ID of a build is not the build ID but the name of the product, the version; the locale and the platform.

**Comment by n1k0** [comment]
Updated issue accordingly.
