### ISSUE TITLE
Important builds entries missing

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/buildhub#109]
I'm super surprised we don't seem to have build records for Firefox 53 en-US stable *at all*: https://mozilla-services.github.io/buildhub/#/builds/product/firefox/channel/all/platform/all/version/53.0/locale/en-US

This is confirmed with the related kinto query: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=10&_sort=-build.date&source.product=firefox&target.version=%2253.0%22&target.locale=en-US

It may be expected because we're still working on fetching information about these, but I felt it was important to create a specific issue.

**Comment by Natim** [comment]
> we don't seem to have build records for Firefox 53 stable at all:

err [we have some](https://mozilla-services.github.io/buildhub/#/builds/product/firefox/channel/all/platform/all/version/53.0/locale/en-US), but it is strange that we don't have the ``en-US`` localized one.

We probably need to find out a way to check that the database is complete.

**Comment by magopian** [comment]
It also seems from the list of channels available at the moment that we're also missing a few of them (nightly, aurora, some others?).

**Comment by n1k0** [comment]
> We probably need to find out a way to check that the database is complete.

Yes, this. Maybe we could add a cron travis job that would check for a few assertions, like ensuring records and filters meet a given set of expectations?

**Comment by mostlygeek** [comment]
I did some analysis. Due to #121 I could only check 10,000 records. 

Out of the 10,000, only 13 have any actual build information. 

```
$curl -s 'https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records' | jq -rc '.data[] | select(.build != null) | {id:.id,bid:.build.id}'

{"id":"firefox_beta_54-0b11_linux-i686_en-us","bid":"20170525225011"}
{"id":"firefox_beta_54-0b13_linux-x86_64_en-us","bid":"20170601203257"}
{"id":"firefox_beta_54-0b12_linux-i686_en-us","bid":"20170529095024"}
{"id":"firefox_beta_54-0b11_linux-x86_64_en-us","bid":"20170525225011"}
{"id":"firefox_beta_54-0b12_linux-x86_64_en-us","bid":"20170529095024"}
{"id":"firefox_beta_54-0b13_linux-i686_en-us","bid":"20170601203257"}
{"id":"fennec_beta_54-0b12_android-api-15_en-us","bid":"20170530075859"}
{"id":"fennec_beta_54-0b12_android-x86_en-us","bid":"20170530075859"}
{"id":"firefox_beta_50-0b7_linux-x86_64_en-us","bid":"20161013141419"}
{"id":"firefox_49-0-1_linux-i686_en-us","bid":"20160922113459"}
{"id":"fennec_beta_50-0b6_android-x86_en-us","bid":"20161010170216"}
{"id":"firefox_beta_50-0b7_linux-i686_en-us","bid":"20161013141419"}
{"id":"firefox_beta_50-0b9_linux-i686_en-us","bid":"20161020152750"}
```

**Comment by leplatrem** [comment]
This was fixed now that we use S3 inventories as the source of info.
