### ISSUE TITLE
Build id information should be a required information

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/buildhub#110]
Right now most build records in the database don't seem to have any `build` object attached to them, while it should contains the build id and build date, which we declared critical information for this project.

For instance, we currently only seem to have 43 build records exposing that information: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=10&_sort=-build.date&source.product=firefox&not_build.id

I think the build objet should be a required information, and/or we shouldn't list builds without that information. A compromise could probably be to have an option in the search UI to allow or disallow listing builds with that information missing.

**Comment by leplatrem** [comment]
Related #19 and #7

**Comment by mostlygeek** [comment]
I agree with @n1k0 that Build Id should be required information. A lot of the consumers of buildhub will probably only have the `build id` and the `release channel` to locate more information about what a user is running.

**Comment by mostlygeek** [comment]
Notes from meeting: 

- @natim said, the Build information is optional (#33) due to us wanting to create the record first and then back fill with the build info from the scraper 
- @Natim to purpose a few options on how to move forward

**Comment by glasserc** [comment]
While #136 provides build IDs for most releases, it doesn't make build ID a required field.

**Comment by Natim** [comment]
> it doesn't make build ID a required field.

As explained before we don't plan on doing that. Because sometimes we need to create the record without a build ID to be able to fill it in later.
