### ISSUE TITLE
We should not rely on Python packaging version_parse to sort version.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#118]
Firefox version builds are not part of the supported by the Python packaging package.

``from packaging.version import parse as version_parse``

Instead we should use the [`build_version_id`](https://github.com/mozilla-services/buildhub/blob/master/jobs/buildhub/index_filters.py#L29) utility in `scrape_archives`.

**Comment by leplatrem** [comment]
Not the case anymore.
