### ISSUE TITLE
WebUI doesn't show total number of records

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#119]
I'm using FF Nightly on OSX.

I cleared the cache and reloaded BuildHub and it seems to continue to show (0 total). The XHR requests look right. I also purged my cache so it reloads all HTML, JS assets again as well. 

The XHR from the server has a `Total-Records: 36452` header so that response is working. No errors in the Web developer console. 

Testing with Safari, Chrome and FFDev Edition on OSX the total record count seems to show up. It appears to be a bug due to changes in FF Nightly.

**Comment by magopian** [comment]
I believe that's also the bug that hit @Natim, can you please confirm?

**Comment by mostlygeek** [comment]
Seems to be a duplicate of #98. Closing in favor of that one.
