### ISSUE TITLE
No OSX Builds?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#120]
https://mozilla-services.github.io/buildhub/#/builds/product/firefox/channel/all/platform/macosx shows nothing. Is this a work in progress or a bug?

**Comment by mostlygeek** [comment]
@leplatrem ?

**Comment by Natim** [comment]
`macosx` doesn't appear to be a platform tag, the platform tag I see here is `mac`.
You can use the filters form to build the URL.

This works fine for me does it for you?
https://mozilla-services.github.io/buildhub/#/builds/product/all/channel/all/platform/mac/version/all/locale/all/buildId//page/1

**Comment by mostlygeek** [comment]
Why do we only have "mac" builds from the nightly release channel?

**Comment by Natim** [comment]
I don't understand the question :/

https://mozilla-services.github.io/buildhub/#/builds/product/firefox/channel/release/platform/all/version/all/locale/all/buildId//page/1

**Comment by Natim** [comment]
Apparently the nightly use platform mac and the release/beta use platform macosx.
Maybe we should use the same plateform for both.
