### ISSUE TITLE
Can not get second page of results from kinto

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#121]
I'm trying to get a full dump of all the builds we currently have aggregated. There seems to be a 10,000 record `kinto.storage.max_fetch_size` so I broke my query up using pagination. However, it seems to be broken: 

The first request, for 9999 records,  tells me there are 36,452 records in total.  

```
$ curl -I 'https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=9999'
HTTP/1.1 200 OK
...
Content-Length: 4180540
Next-Page: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tOGVkMTAxM2UtOGI5OC00YmM2LTg3YmMtZWI0N2EzNTkwZTVjIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5MjkzNzQzNH0sIm9mZnNldCI6OTk5OX0%3D&_limit=9999
Total-Records: 36452
...
````

It also responds with the correct number of records: 

````
$ curl -s 'https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=9999' | jq '.data | length'
9999
````

My second request for the `Next-Page` url is a total fail. 

````
$ curl -I 'https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tOGVkMTAxM2UtOGI5OC00YmM2LTg3YmMtZWI0N2EzNTkwZTVjIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5MjkzNzQzNH0sIm9mZnNldCI6OTk5OX0%3D&_limit=9999'

HTTP/1.1 200 OK
...
Content-Length: 420
Total-Records: 36452
...
````

The body is also totally wrong:

````
$ curl -s 'https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tOGVkMTAxM2UtOGI5OC00YmM2LTg3YmMtZWI0N2EzNTkwZTVjIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5MjkzNzQzNH0sIm9mZnNldCI6OTk5OX0%3D&_limit=9999' | jq '.data | length'
1
````

These are the problems: 

1. No data in the second request 
1. The second request does not have a `Next-Page` header

**Comment by magopian** [comment]
It seems that the 10000 server limit is enforced on the number of records that have been queried, and not the number of records returned.

Eg: using `_limit=5000` will allow two requests to be made and "succeed" (with proper content and `Next-Page` headers). Using `_limit=100` will allow 100 requests. But using `_limit=10000` will only allow one.

At least that's from my experiments.

**Comment by leplatrem** [comment]
Good catch, we'll investigate that on in Kinto/kinto#1266

**Comment by mostlygeek** [comment]
Can we close this bug now that it's fixed in Kinto?

**Comment by leplatrem** [comment]
Yep, kinto 7.2.0 was just deployed on kinto-ota
