### ISSUE TITLE
About searchkit ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#127]
SearchKit is a suite of UI components to create beautiful search applications using declarative React components.

Following the tutorial and with a few lines of code, it is possible to obtain a UI like that one:

![screen shot 2017-06-07 at 17 03 09](https://user-images.githubusercontent.com/546692/26885557-3d8dd3d4-4ba3-11e7-9850-7a3efde2c85e.png)

The code [is in there](https://github.com/mozilla-services/buildhub/tree/try-searchkit/ui/elastic)

**Comment by magopian** [comment]
Seeing this, I believe it would make sense to take a couple of "use case requirements" and see how to fulfill them with searchkit. There's no point in implementing and maintaining our own "in-house reinvented wheel" if this works.

Here's a few things I'd like to experiment:
- searching for a given build ID
- filtering out null/missing build IDs
- changing some values to be links (eg links on the revisions)
- pagination (is it built-in?)
- link to a specific build record (is it built-in?)
- build record details page

**Comment by magopian** [comment]
- [x] searching for a given build ID: sure thing, built-in
- [ ] filtering out null/missing build IDs: do we need that? We don't currently have this feature in buildhub
- [x] changing some values to be links (eg links on the revisions): yep, by using a custom `listComponent` or `itemComponent`
- [x] pagination (is it built-in?): yes, built-in
- [x] link to a specific build record (is it built-in?): built-in, each and every filter/query has its ow url (based on query string parameters)
- [ ] build record details page: not built-in, but we might not need one (we don't currently have one in buildhub)

**Comment by leplatrem** [comment]
Mago, I understood that lately most efforts were invested in the searchkit UI. What do you think we should do?

With the current needs that were expressed in terms of UI (ie, browse content and validate completeless), do you think that searchkit does a better job than the elm-catalog ? Should we «decommission» the elm one (and mark its related issues as wont-fix) ? `#ColdHeart`

**Comment by magopian** [comment]
I'm not sure exactly what are the current unsatisfied needs in the Elm and/or searchkit version, are there any?

I don't think any of those two solutions is better suited (or does a better job) per say. The Elm version is far more versatile, the searchkit one is far smaller and simpler (as long as we don't have to go around the searchkit library, which we didn't have to do yet).

From what I've seen, there's currently only one standing issue for the Elm version: #172, am I missing something? It's a trivial bug to fix, so what I guess I'm saying is:

whatever

I guess with the current interdiction to ship anything in Elm, and the fact that the searchkit solution is simpler and sufficient as it is, we could decommission the Elm version.

**Comment by mostlygeek** [comment]
I agree with @magopian. Plus I was told pretty plainly we're not shipping Elm in the near term. We can close this issue and ship SearchKit.
