### ISSUE TITLE
Kinto or ElasticSearch ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#128]
Currently we have Kinto in charge of the (long term) persistence using PostgreSQL and a ElasticSearch plugin that replicates the incoming data into a very fast index with aggregation features.

Both provide a JSON API. What are the real benefits of keeping both? Shouldn't we keep only one instead of this hybrid approach in the long term?

**Comment by glasserc** [comment]
The current thinking on the subject appears to be:

- The BuildHub UI can be driven entirely by ElasticSearch and it's quite fast, so for that we can just use ElasticSearch.
- The Kinto API is nicer than the ElasticSearch API both for adding data as well as accessing data, so we expect most clients to use the Kinto API.
- ElasticSearch is not really meant to be a persistent data store, but Kinto is, so it's not unreasonable to keep data in Kinto. This permits reindexing during cases like #126.

I don't have a strong opinion but to me, this argues in favor of keeping both.

**Comment by n1k0** [comment]
What @glasserc said.

**Comment by leplatrem** [comment]
Thanks for your answers!
