### ISSUE TITLE
The search endpoint retrieve all results by default

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/buildhub#130]
GET http://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/search

This seems trying to render all the results, making the server stale for a while, which is probably not what we want.

**Comment by n1k0** [comment]
The request times out anyway

![](http://i.imgur.com/dtFZqLq.png)

DDoS as a Service!

**Comment by leplatrem** [comment]
Good catch, we should use the `kinto.paginate_by` setting.

**Comment by Natim** [comment]
Is there a mecanism for elasticsearch to paginate the response?

**Comment by n1k0** [comment]
Yes, `size` and `from` as per the current Elm implementation.

**Comment by leplatrem** [comment]
Was released in kinto-elasticsearch 0.2 (and deployed on ota)
