### ISSUE TITLE
Update default ES results sorting to -version  

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/buildhub#133]
Right now the results seems to be sorted in some random order, so we have firefox 17esr listed first. We should rather sort builds by version desc.

**Comment by Natim** [comment]
Also note that if you want to order by version you would need to store this `versionshort` value somewhere: https://github.com/mozilla-services/buildhub/blob/master/jobs/buildhub/index_filters.py#L29-L48

**Comment by n1k0** [comment]
If gonna look for computed sort values with ES, but it would definitely be easier if this field would be naturally part of the data model.

**Comment by leplatrem** [comment]
Is this still relevant @magopian ?

**Comment by magopian** [comment]
nope ;)
