### ISSUE TITLE
Allow multiple values in filters

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#139]
I would like to be able to select multiple values for filters. For example, I would like to select: 

Product: Firefox
Channels: Release
Versions: 53.0, 53.0.2, 53.0.3

**Comment by n1k0** [comment]
Very good idea! Also that's gonna be a good flexibility benchmark between Elm and searchkit 😊

**Comment by magopian** [comment]
It's nearly a one-liner in searchkit: https://github.com/mozilla-services/buildhub/pull/135/commits/47daf9fc12889fb2c73392cd5b98f02c68ff16c9

![screenshot from 2017-06-13 10-25-46](https://user-images.githubusercontent.com/167767/27073065-dc7223c8-5022-11e7-81de-29bc28f88ae8.png)

**Comment by n1k0** [comment]
Ongoing implementation is currently happening in #155.

**Comment by magopian** [comment]
Support for this feature is now live in both frontends (elm and searchkit)
