### ISSUE TITLE
hyphens in the locale filter should not create new options

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#140]
![screen shot 2017-06-12 at 11 29 25 am](https://user-images.githubusercontent.com/83972/27048918-78732414-4f62-11e7-8a5d-e0e2a6155eca.png)

This should produce a list of: 

* "en-GB"
* "en-US"
* "en-ZA"

**Comment by n1k0** [comment]
This should be fixed by #126 which has landed but has not been deployed to production yet it seems.

**Comment by magopian** [comment]
It is now live and in production \o/
