### ISSUE TITLE
Remove the sum for the "all" option

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#141]
![screen shot 2017-06-12 at 11 32 41 am](https://user-images.githubusercontent.com/83972/27049025-e127d9b4-4f62-11e7-9620-04421f5d00d8.png)

The sum or `all` is misleading. We should just remove it.

**Comment by n1k0** [comment]
The counts are actually weird, maybe I introduced a bug lately. Eg. here it makes no sense to have the same total count as with the `es` value; basically the sum of all filters should be the count next to `all`.

**Comment by n1k0** [comment]
To be noted that atm the fix for having strings containing hyphens properly indexed and enumerated in ES has not been deployed to production it seems. Maybe that's why the counts are strange?

**Comment by Natim** [comment]
The count are strange only if you select a filter. In Benson example es is selected so all refers to only es builds.

**Comment by n1k0** [comment]
Ah right, so a proper fix would be to hide the all count when a filter is selected.
