### ISSUE TITLE
[searchkit] hitsPerPage isn't taken into account

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#147]
It's currently [set to 30](https://github.com/mozilla-services/buildhub/pull/135/files#diff-2fa7cb8d5e63a125ff5319ae783b8ea5R180) but we're getting back (and displaying) 1000 as can be seen on the right in the following screenshot:

![screenshot from 2017-06-14 09-17-51](https://user-images.githubusercontent.com/167767/27120030-5d0f937a-50e2-11e7-9a0c-fd1b72e1697d.png)

**Comment by magopian** [comment]
@leplatrem @Natim it seems the size is properly sent as a parameter to the endpoint, as can be seen in the following screenshot:

![screenshot from 2017-06-14 10-02-29](https://user-images.githubusercontent.com/167767/27121707-b13ed27a-50e8-11e7-925c-80cf24cc5e2c.png)

Any idea why we're still getting 1000 records back? Maybe some elasticsearch configuration or something?

**Comment by Natim** [comment]
Might be related to https://github.com/Kinto/kinto-elasticsearch/pull/46/files#diff-e451f5219e86e5932f24e35cdc3dd7e6R37 it something we should figure out.

**Comment by magopian** [comment]
Indeed, it's not taking the `size` parameter at all. I'm removing the `webui` label ;)

**Comment by n1k0** [comment]
It works in the Elm version, I think the `size` property must be part of the `query` object.

**Comment by leplatrem** [comment]
I'll check on the kinto-elasticsearch side in the mean time

**Comment by n1k0** [comment]
Wait, no, there has been a regression on the server because the Elm version now lists 10k records as well, what it was working just fine a few days ago and the Elm codebase hasn't been touched meanwhile.

**Comment by leplatrem** [comment]
Fixed, released and deployed kinto-elasticsearch 0.2.1.

Close if you're happy with the current behaviour :)

**Comment by magopian** [comment]
Wow that was SUPER fast, thanks a lot @leplatrem <3

**Comment by n1k0** [comment]
Has the patch been deployed to production? The Elm version still lists 10k records atm.

**Comment by magopian** [comment]
It does fix the searchkit version: https://mozilla-services.github.io/buildhub/searchkit/ displays only 30 entries.

**Comment by n1k0** [comment]
Ah no, cache issue it seems, works fine now.
