### ISSUE TITLE
Find a way to order versions numerically and not alphabetically

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#149]
There's various ways to do that:
1/ store a "orderable version" (see https://github.com/mozilla-services/buildhub/issues/133#issuecomment-307763965)
2/ use the proper collation (see https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html)
3/ sort using a script, aka computed field sorting (see http://www.elasticsearch.org/guide/reference/api/search/sort.html : sorting with a script)

**Comment by n1k0** [comment]
While relying on ES native features might sounds to be the best plan, we need to consider making achieving the same using Kinto, so the orderable field might be the easiest for consumers.

**Comment by magopian** [comment]
I see there's a version `namoroka`: is that an error, or should we expect such version numbers @leplatrem @Natim ?

Currently in the searchkit version we're "manually" sorting on the client by major only. I'm going to give a shot at implementing it so it also sorts by minor and patch.

I believe this is "good enough" for the client itself. Not sure if we'd like/want to have such sorting on the server (adding a feature to kinto) (ping @leplatrem @Natim )

**Comment by Natim** [comment]
The last version of the scraping script fixes this version error.

**Comment by magopian** [comment]
so we have a bunch of weird versions that don't even conform to some weird versioning:

```
namoroka
4.2a1pre
4.0b9pre
4.0b8pre
4.0b7pre
4.0b6pre
4.0b5pre
4.0b4pre
4.0b3pre
4.0b2pre
4.0b13pre
4.0b12pre
4.0b11pre
4.0b10pre
4.0a1pre
38.0b8-2
38.0.5b1-2
3.7a6pre
3.7a5pre
3.7a4pre
3.7a3pre
3.7a2pre
3.7a1pre
3.6a2pre
3.6a1pre
3.2a1pre
3.1b3pre
3.1b2pre
3.1b1pre
3.1a2pre
3.1a1pre
3.0.19-real-real
3.0.16-real
29.0-funnelcake31
29.0-funnelcake30
24.0-funnelcake25
24.0-funnelcake24
22.0-funnelcake23
21.0b2-bad
10.0-real
```

I've tried a few npm libraries to do the sorting, and the one that seems to cope the best with our versioning scheme seems to be https://www.npmjs.com/package/version-sort (but even this one fails on those above).

So either we decide that ordering on major is sufficient, either i'm going to implement a solution myself.

**Comment by mozbhearsum** [comment]
This won't cover all cases, but https://github.com/mozilla/balrog/blob/master/auslib/util/versions.py might be a source of inspiration to handle some. It covers things like a1, b2, pre, plugin.

**Comment by ochameau** [comment]
Firefox internal implementation lives here:
http://searchfox.org/mozilla-central/source/xpcom/base/nsIVersionComparator.idl
http://searchfox.org/mozilla-central/source/xpcom/base/nsVersionComparator.cpp
http://searchfox.org/mozilla-central/source/xpcom/tests/unit/test_versioncomparator.js

**Comment by magopian** [comment]
The way it's done in addons-server: https://github.com/mozilla/addons-server/blob/master/src/olympia/versions/compare.py
