### ISSUE TITLE
[searchkit] document how the searchbox works

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#151]
At the moment, there's no indication that the searchbox is only searching on the build IDs, nor that it needs a `*` to match partial IDs.

Maybe we can change the search to work as a search on the prefix?

**Comment by n1k0** [comment]
Also searching for `firefox` in the main search box retrieves no results, which might be confusing to users. We may want to search in other fields with this search box.

**Comment by magopian** [comment]
"Documented" it using a placeholder:

![screenshot from 2017-06-14 10-45-14](https://user-images.githubusercontent.com/167767/27123584-9bc685d6-50ee-11e7-8c12-e932aee0ac4d.png)

We can add more fields to search on if we want to, but then we would diverge from the behavior we have in the elm version (and also it feels sometimes a bit confusing, because you can't always tell why a record is returned, not knowing on which (invisible?) field it was matched).

**Comment by n1k0** [comment]
Yeah I dunno, I'd heavily suspect newcomers to just search like they would do with google, like "firefox 52 mac" or smthg. It's probably ok like this, no big deal.

**Comment by magopian** [comment]
Fixed by https://github.com/mozilla-services/buildhub/commit/ee8331de6023e22a87fe9560fec4f6882b034c15
