### ISSUE TITLE
[searchkit] using "view more" on very long list of values for filters (eg "versions") is cumbersome

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#152]
We could have more versions displayed by default, but it would then use more real estate. The other option would be to have a select instead, but it would prevent selecting multiple versions (unless we implement/use a clever react component that would be a select of checkboxes?).

**Comment by n1k0** [comment]
We could use a `<select multiple/>` tag.

**Comment by magopian** [comment]
That, or not change anything once #149 is fixed: we'll then have the latest versions displayed first, which should be the ones queried the more often?

**Comment by magopian** [comment]
I've experimented adding a `max-height: 300px; overflow: scroll;` to the panels, and it seems to do the job:

![screenshot from 2017-06-15 10-26-47](https://user-images.githubusercontent.com/167767/27172363-3b63c42a-51b5-11e7-9f09-fb80eaf7207e.png)

Another idea could be to try using http://jedwatson.github.io/react-select/ but i'm not sure how feasible it'll be to integrate it with searchkit.

**Comment by magopian** [comment]
The code is in https://github.com/mozilla-services/buildhub/pull/135/commits/6437675b33982c878f89683c74e48749edaa5e37

@n1k0 thoughts?

**Comment by n1k0** [comment]
Would be nice to hide the horizontal scrollbar at the bottom:

![](http://i.imgur.com/perGfqb.png)

Apart from that, wfm

**Comment by magopian** [comment]
Fixed in https://github.com/mozilla-services/buildhub/pull/135/commits/f556884bc3fd5eff0f67270319d56d21ed3b00e8, thanks!
