### ISSUE TITLE
[searchkit] Is there a way to create custom filters like: `Id: 201706*`? 

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#154]

**Comment by n1k0** [comment]
In the Elm version I forged a custom query using a [`prefix` clause](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html), dunno for searchkit.

**Comment by magopian** [comment]
@mostlygeek are you talking about a filter that would be displayed as a button, which would do the query automatically when pressing it?
Or are you talking about custom queries in the search box, to allow one to search for terms in a given field?

From what I could see, none of those two features are provided by searchkit. I believe the first one could be done rather easily with a custom react component, for the second, i'm not sure, it might need a plugin or something on the elasticsearch server.

**Comment by magopian** [comment]
After discussing this issue with @mostlygeek the idea is to have a way to specify filters/fields straight into the searchbox, eg `version:54 id:201706`

**Comment by magopian** [comment]
So it seems it's already doable/usable in searchkit as is, using elasticsearch's [Query String Syntax](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-query-string-query.html#query-string-syntax). The caveat being that to search for firefox, you'd have to put the full field name: `source.product:firef*`

**Comment by magopian** [comment]
Do we want to document that, or maybe add a link to the elasticsearch query docs?
