### ISSUE TITLE
[elm-ui] No style with Nightly?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#160]
Works with stable Fx 54 but with Nightly:

![screenshot from 2017-06-15 11-28-04](https://user-images.githubusercontent.com/546692/27174847-c4edd980-51bd-11e7-9b74-17df2ebeea2b.png)

**Comment by n1k0** [comment]
Fixed by https://github.com/mozilla-services/buildhub/commit/68f2ce07c3c8be542a128ba74b72a43146c90950.

**Comment by leplatrem** [comment]
@n1k0 the problem seems to have come back. But I can't see any weird characters in the CSS so I can't say...

**Comment by n1k0** [comment]
Hmm works for me with the very latest nightly. Have you tried turning it^W^W force refreshing the page?

**Comment by leplatrem** [comment]
I'm sorry. Privacy Badger was blocking bootswatch
