### ISSUE TITLE
Filtering multiple values in Elm frontend seems broken

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#163]
Lists the correct number of records: 
![screen shot 2017-06-15 at 1 25 34 pm](https://user-images.githubusercontent.com/83972/27200349-43df0fb0-51ce-11e7-837d-6d1169b8d5fa.png)

Adding `Version: 55..0b1 (8)` causes search to find *all* firefox records. 

![screen shot 2017-06-15 at 1 26 17 pm](https://user-images.githubusercontent.com/83972/27200348-43dee2d8-51ce-11e7-8533-328c85361ef8.png)

**Comment by n1k0** [comment]
Indeed, I need to fix the ES query. Will do in #155.
