### ISSUE TITLE
Store version build attribute

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub#178]
It seems like buildhub isn't scraping the candidates directories. For example:

https://archive.mozilla.org/pub/firefox/candidates/45.3.0esr-candidates/build1/

The `build1` part of the url is the `version_build` which Socorro captures for releases, betas, and esrs. I'm not sure what Socorro does with those, yet, but it's not in the buildhub data.

**Comment by mostlygeek** [comment]
afaik candidates don't have a lot of value. They're only for internal testing purposes and never released to the actual public.

**Comment by lonnen** [comment]
@mostlygeek can you clarify `internal testing purposes`? Most crash-stats users are internal and may be running weird builds. Trying to determine the value of these builds. That directory is covered by the extant ftpscraper in crash stats.

**Comment by mostlygeek** [comment]
It was explained to me that `candidate` builds are for QA to test a build for Release. Once approved they're essentially copied over to the `releases/` path on archive.  They're never directly released to the public on any channel. I'm assuming they'll only be used by a handful of people. 

Maybe @bhearsum can shed more light if I've misunderstood anything.

**Comment by leplatrem** [comment]
The loading of ESR records was fixed now that we use S3 inventories. 
https://mozilla-services.github.io/buildhub/searchkit/?versions[0]=45.3.0esr&channel[0]=esr

However, we don't keep the `version build` attribute, so I'm retitling this issue
