### ISSUE TITLE
ability to view a specific build in ui

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub#180]
The ui at https://mozilla-services.github.io/buildhub/#/builds is great for looking for groups of builds, but there doesn't seem to be a "details" view for the rows in that table.

Is there any way to view the details for a specific row?

Amongst other things, this will help in writing up issues for data problems. Then I can list links to details for builds that illustrate the problem.

**Comment by n1k0** [comment]
Yeah that's a missing feature I was planning to work on, thanks for filling the issue!

**Comment by willkg** [comment]
PR #181 doesn't really help my major use case. It lets me see details for a build, but it's interpreting the data and changing it. Further, it's not linkable. So it doesn't help me write up issues with data problems.

However, I think I can solve my use case by using API urls and the `id` field. For example, this:

https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/archives/records?id=firefox_nightly_2017-06-10-10-02-01_55-0a1_linux-x86_64_en-us

I think that'll work good enough.

Thank you!

**Comment by Natim** [comment]
You should use the record URL then: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records/firefox_nightly_2017-06-10-10-02-01_55-0a1_linux-x86_64_en-us

**Comment by willkg** [comment]
It looks like that url is from the releases collection. I thought I was supposed to be using the archives collection. Should I be using a different one now?

**Comment by Natim** [comment]
I am sorry for the misunderstanding.

We have been loading records in multiple collections but the current provisioned one is `release`, as soon as the production stack is deployed it won't change anymore.
