### ISSUE TITLE
Add a normalized platform field

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#184]
We can see strange things like: win32-sha1 or funnelcake etc.

Should we settle on an exhaustive list instead?

- macosx
- linux-i686
- linux-x86_64
- win32
- win64
- android-arm
- android-x86
- mac-ppc
- maemo

What are the following meaning:

- android-aarch64
- android
- android-api-9
- android-api-11
- android-api-15
- win32-EME-free
- win64-EME-free
- win32-EUballot
- mac-EME-free
- linux-x86_64-EME-free
- win32-sha1
- win64-sha1
- android-armv6
- mac64
- maemo4
- maemo5-gtk
- android-r7
- android-xul
- win32-EUballot-rc2
- wince-arm
- win32-funnelcake26
- win32-funnelcake27
- win32-funnelcake28
- win32-funnelcake29

**Comment by n1k0** [comment]
+1 for standardizing platform names.

**Comment by Natim** [comment]
However I don't know who can signoff for the list.

**Comment by n1k0** [comment]
how 'bout just us

**Comment by willkg** [comment]
If you plan to normalize the platform names, can you put the un-normalized original platform name somewhere?

**Comment by Natim** [comment]
You mean in another field? Do you have a list of the platform you support for instance? What are the information you are expecting here? Are you expecting some of the second list ones?

**Comment by n1k0** [comment]
We could also split the platform string into two distinct values, like `{"family": "android", "flavor": "arm"}` or smthg like that, then retrieving the original would be matter of joining the two pieces.

**Comment by willkg** [comment]
Yes, I think we should store the original platform in another field.

Those platform names aren't random and they do have meaning. I think normalizing them will help some use cases, but having the original ones will help others.

Socorro's ftpscraper normalizes builds for beta, devedition, and release:

* mac
* linux
* win
* android

Then for nightlies, it keeps the original platform name. For example:

* linux-i686
* linux-x86_64
* win32
* win64

I'm not entirely sure how that information is used across Socorro, yet, but that's what ftpscraper does currently.

If you do plan to normalize it, how would you deal with new platforms that your system doesn't know how to normalize?
