### ISSUE TITLE
Deterministic records ids

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#20]
Currently we let the server choose the records ids (using POST).

@Natim suggested that we could have a relation between a release and its record.

Idea: We could use the download url (which is unique) to compute a uuid for example.

**Comment by Natim** [comment]
My understanding after discussions is that we can use the following format to generate an unique ID for an archive.

```{product_name}/{channel}/{version}/{platform}/{locale}```

e.g: firefox/release/53.0b9/linux-i686/en-US

I would recommand using MD5 to generate a unique ID from it.

```python
>>> from uuid import UUID
>>> from hashlib import md5
>>> UUID(bytes=md5(b"firefox/release/53.0b9/linux-i686/en-US").digest())
UUID('50b4c8af-0cc3-fdea-ba3b-21e70d8e2404')
```

**Comment by Natim** [comment]
Question from @glasserc:

Why not use directly: firefox_release_53.0b9_linux-i686_en-US

**Comment by leplatrem** [comment]
I'm not sure if `channel` should be part of it

**Comment by leplatrem** [comment]
And what about two consecutive nightlies? (same version, same channel)

**Comment by Natim** [comment]
Today channel is part of the URL.
What is the URL for nightly version?

**Comment by Natim** [comment]
And for mobile:

``fennec_releases_39.0b5_android-api-9_sl``

**Comment by Natim** [comment]
Here is a gist of how it looks like: https://gist.github.com/Natim/049361533ccb861c2d770835ea188575
