### ISSUE TITLE
System-addons information

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#202]
We could have a collection of system-addons records. The question we want to answer is: what systemaddons (id + version) are shipped with a particular release and what updates users are supposed to run

We already had implemented the code:

* Download archive and inspect browser/modules content https://github.com/mozilla-services/buildhub/blob/5a6546bd368fcb7e566ebade9e1383b7c49583b8/jobs/inspect_archives.py
* Fetch update info from Balrog : https://github.com/mozilla-services/buildhub/blob/ca149b762faf2dc66385bb56698fcfae14648112/jobs/buildhub/sysaddons_updates.py

But there more that 300K records for Firefox builds, not all are relevant regarding system-addons since they appeared recently, but still, downloading 50M from archive and extracting them to inspect their content seems a bit airy-fairy.

We can get back on that after 1.0 with a finer strategy if it makes sense

**Comment by mostlygeek** [comment]
Do we need to download all 300K Fx builds? 

As a start I think we should limit ourselves to: 

* download only the last year worth of builds 
* download only linux releases. System addons are the same across a version I believe. 
  * these are the easiest to unpack vs windows right?

How many builds do we need to process in that case?

**Comment by leplatrem** [comment]
Something like 1000 records if we focus on English Linux 64bits above version 50.
A bit more that a 100 if we exclude nightlies...

`http HEAD 'https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?source.product=firefox&target.platform=linux-x86_64&target.locale=en-US&min_target.version="50"'`

**Comment by leplatrem** [comment]
This feature would require a whole new cycle of specifications, design, and cross-team efforts. I'm closing for now.
