### ISSUE TITLE
Check that scraping script can be resumed easily

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#21]
Currently, we take the highest version on the remote storage to resume a previous run.

It should work ok as long as things go well. But if a scraping task crashes, it can leave some records out for specific locales, platforms or whatever.

We should elaborate a clear strategy to allow idempotence/resuming efficient :)

**Comment by Natim** [comment]
I'd like to work on a similar strategy that we used for XML Blocklists, get all the archive and then findout the one that changed or are inexistent or incomplete.

**Comment by leplatrem** [comment]
> get all the archive and then findout 

scanning the whole archive repo is very (very) costly

**Comment by mostlygeek** [comment]
Scraping is really a backfilling strategy. I think getting most of the info from Pulse (pushed to us) would be ideal. If pulse is lacking info, it's not beyond our means to help update systems so we get a complete view of the data.

**Comment by leplatrem** [comment]
Why not. But we'll want to be able to resume backfilling scripts anyway :)

**Comment by leplatrem** [comment]
Now that we use S3 inventories, the user story is different: 

* we download the S3 inventory for the day
* we parse the resulting CSV
* we load the records into Kinto using `to-kinto --skip` which skips records that are already there (and whose fields are equal).

So, I propose that we mark the issue as resolved (by #185 )
