### ISSUE TITLE
Obtain the locale revision

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#22]
Somewhere (ShipIt at least), there is the mercurial changeset of the locale that was used to build the release. Find out how to get that :)

**Comment by leplatrem** [comment]
Example:
* Fetch from product details: `https://product-details.mozilla.org/1.0/l10n/Firefox-54.0beta.json`
* For each language provide repository/tree info: https://hg.mozilla.org/releases/l10n/mozilla-beta/fr/rev/661e5ad66451

Should we keep `locale` in target? Or should it a be a dedicated attribute `locale` with all `name`, `changeset`, `repo`?

**Comment by Natim** [comment]
```
        {
            "id": "thunderbird_11-0b5_linux-x86_64_ga-ie",
            "product": "thunderbird",
            "channel": "beta",
            "platform": "linux-x86_64",
            "version": "11.0b5"
            "source": {
                "repository": null,
                "revision": null,
                "tree": null
            },
            "locale": {
                "id": "ga-IE",
                "repository": null,
                "revision": null,
                "tree": null
            },
            "download": {
                "date": "2015-10-16T05:33:23Z",
                "mimetype": "application/x-bzip2",
                "size": 22172953,
                "url": "https://archive.mozilla.org/pub/thunderbird/releases/11.0b5/linux-x86_64/ga-IE/thunderbird-11.0b5.tar.bz2"
            }
}
```

**Comment by leplatrem** [comment]
The move of target to the root is not a bad idea, but it's not directly related I think.

We could also have something like this:

```js
"source": {
  "repository": "...",
  "revision": "...",
  "tree": "...",
  "locale": {
    "repository": "...",
    "tree": "...",
    "revision": "...",
   }
}
```

**Comment by leplatrem** [comment]
Also available in archives m org https://archive.mozilla.org/pub/firefox/candidates/54.0b9-candidates/build1/l10n_changesets.txt

**Comment by leplatrem** [comment]
Closing because nobody clearly asked for this. Reopen if I'm wrong.
