### ISSUE TITLE
Lots of 503 and 504 in stage

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#232]
We need to figure out how to pause the loading in case we have a 503 or a 504 so that we don't miss out a lot of records.

**Comment by leplatrem** [comment]
Do we miss them in the end? I think that it raises if the requests failed after the X retries

**Comment by Natim** [comment]
Taking down the number of thread to 1 fixes the issue.

**Comment by Natim** [comment]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1380695#c23
