### ISSUE TITLE
In Fennec records, repository, tree and revision are empty.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#31]

**Comment by leplatrem** [comment]
Can you confirm that is still true for every record? They should only be empty for old versions and non american english locales (see #19)

**Comment by leplatrem** [comment]
Indeed:
https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records/fennec_51-0b1_android-x86_en-us
Should have info from:
https://archive.mozilla.org/pub/mobile/candidates/51.0b1-candidates/build3/android-x86/en-US/fennec-51.0b1.en-US.android-i386.json
