### ISSUE TITLE
OS X builds missing since 58.0b4

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-services/buildhub#327]
I was exploring the buildhub data a bit and discovered that OS X builds are missing from Firefox (maybe other applications too) since 58.0b4: https://mozilla-services.github.io/buildhub/?versions[0]=58.0b4rc1&products[0]=firefox

If I go one release back (https://mozilla-services.github.io/buildhub/?versions[0]=58.0b3rc2&products[0]=firefox) they are present again.

**Comment by Natim** [comment]
Is there a reason why you use the candidate version number rather than the beta version number?

For instance 58.0b4 works: https://mozilla-services.github.io/buildhub/?versions[0]=58.0b4&products[0]=firefox

**Comment by leplatrem** [comment]
> I guess that's because buildhub processed them so quickly that only linux was built at the time?

That can't be the reason, because the lambda is triggered every time a new file is uploaded there.

**Comment by leplatrem** [comment]
A lot versions are missing for Mac OS:
https://mozilla-services.github.io/buildhub/?platform[0]=macosx&products[0]=firefox
![screenshot from 2018-01-25 16-15-17](https://user-images.githubusercontent.com/546692/35395574-03ec8b12-01eb-11e8-88c7-184513b96068.png)

And 58.0 only has Linux :( 
https://mozilla-services.github.io/buildhub/?versions[0]=58.0&products[0]=firefox

**Comment by peterbe** [comment]
Let's see if I understand this correctly. 
<img width="1616" alt="screen shot 2018-03-21 at 2 02 35 pm" src="https://user-images.githubusercontent.com/26739/37728481-ba982100-2d10-11e8-9944-ba5e8c2876e0.png">
At the time of writing, there is only the Linux platform for 60.0b5. :(
https://mozilla-services.github.io/buildhub/?versions[0]=60.0b5&products[0]=firefox

In the [candidates folder](https://archive.mozilla.org/pub/firefox/candidates/60.0b5-candidates/build1/) there are releases for other platforms. [E.g mac](https://archive.mozilla.org/pub/firefox/candidates/60.0b5-candidates/build1/mac/en-US/)

The cronjob executes at **17:00 UTC every day**.
At the time of writing, that means 1h15min ago and according to @bqbn it's actively ongoing. Like, right now. 

The [win64](https://archive.mozilla.org/pub/firefox/candidates/60.0b5-candidates/build1/win64/en-US/) version was added there at `2018-03-19T22:51:07Z` which is roughly 1 and a half day ago. Meaning, if the Lambda did fail, the cronjob has had a chance to remedy it in theory. But it clearly hasn't done so. :(

**Comment by peterbe** [comment]
And voila! Now it's there!

<img width="1616" alt="screen shot 2018-03-21 at 2 31 17 pm" src="https://user-images.githubusercontent.com/26739/37729897-9ccc8da6-2d14-11e8-958b-f07a98885047.png">

This means that the cronjob is saving our bacon. Depressing that it had to take MORE than 1 day to get it right. 

It smells to me that both 
* the Lambda event failed
* the cronjob had a chance yesterday but seems to have failed

Because this issue is intangible to action and because we've discussed other grander plans to better avoid errors like this in the future I'm going to boldly close this.
