### ISSUE TITLE
Issue (or not ?) with 59.0b1

### ISSUE THREAD

**Issue by calixteman** [mozilla-services/buildhub#328]
When I look on buildhub for 59.0b1, I got:
-buildid 20180113035635
-rev 0f6772
When I look on archive.mozilla.org (https://archive.mozilla.org/pub/devedition/releases/59.0b1/SOURCE):
- rev 2c42f976a8bb555562f26777e6a6905950f6409d
- this rev corresponds to the one for 59.0b1rc11 (according to buildhub)
The pushlog between these two revisions is:
https://hg.mozilla.org/releases/mozilla-beta/pushloghtml?fromchange=0f677284ab9bbb7663f3d47f464c43bb98ad0ead&tochange=2c42f976a8bb
and according to this it seems that rev 0f6772 is still in 58b branch.

Anyway, I expect for b1 to have the data for the "true" b1 and not for something else.

**Comment by Natim** [comment]
We'd like to fix that before 60.0b1 (2018-03-12)

**Comment by leplatrem** [comment]
For the reference, the Kinto record:
https://archive.mozilla.org/pub/devedition/candidates/59.0b1-candidates/build11/linux-x86_64/en-US/firefox-59.0b1.json

**Comment by leplatrem** [comment]
Ok, got it. The problem comes from the build folder name sorting (`build9` < `build11`)

It takes it from here (cause it considers it the latest):
https://archive.mozilla.org/pub/devedition/candidates/59.0b1-candidates/build9/linux-x86_64/en-US/firefox-59.0b1.json
