### ISSUE TITLE
Disable logging of backoff/retries

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#333]
We should not log requests retries as errors, until they fail ( #330 )

**Comment by leplatrem** [comment]
https://github.com/litl/backoff/blob/231a804ceac5da262d5a0835e95a2ae58cc6427b/README.rst#logging-configuration

**Comment by leplatrem** [comment]
Seems like current configuration is fine. It logs an error when retries are exceeded.

**Comment by leplatrem** [comment]
Maybe not?
![screenshot from 2018-02-21 12-04-02](https://user-images.githubusercontent.com/546692/36476863-6302064e-16ff-11e8-8625-ad260466a30f.png)

**Comment by Natim** [comment]
Maybe getting a giving up is a good thing?

**Comment by leplatrem** [comment]
> Maybe getting a giving up is a good thing?

Yeah but the two others are useless IMO

**Comment by peterbe** [comment]
Depending on https://github.com/mozilla-services/buildhub/pull/358
