### ISSUE TITLE
*.zip and *.installer.exe are mixed

### ISSUE THREAD

**Issue by calixteman** [mozilla-services/buildhub#338]
here: https://mozilla-services.github.io/buildhub/?platform[0]=win64&channel[0]=nightly&locale[0]=en-US&products[0]=firefox
we can see that for win32 and win64, .zip and .installer.exe are mixed (it's visible on column "Size").

**Comment by leplatrem** [comment]
We can't know in advance which archive will come first on S3.
I would be tempted to believe that the second one overwrites the record coming from the first archive.

Would you have a preference? Looks like .exe is everywhere whereas zip are just for nightly no?
