### ISSUE TITLE
Automate release steps

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/buildhub#346]
Per https://github.com/mozilla-services/buildhub/pull/345#issuecomment-365978068, it's often better for release steps to be automated than documented. A good platform for the automation of release steps might be zest.releaser and its hooks.

**Comment by peterbe** [comment]
Ethan documented the release/deploy steps and in [this PR](https://github.com/mozilla-services/buildhub/pull/422) and turned those documented steps into a Python script. 

The full deploy process still contains some manual steps. I.e. the `bin/deployment-bug.py` just helps you get a link to file a bug for OPs.

With that in mind I'm going to boldly close this issue for now.
