### ISSUE TITLE
Consolidate Circle, Travis and tox

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub#357]
At the moment, we use Travis in PRs. Travis triggers tox. On master builds we use Circle *and* Travis. 

There's definitely a cost of maintaining all three. Can we "clean this up" so there's only 1 single thing that runs all the tests (linting, unit, functional, etc)?

Goals;
* Have fewer ways to run tests
* One file or script to check everything in PRs
* Be smart about things that are only applicable in PRs or only applicable in master/tag builds. But let's not over-engineer the distiction.
* Devs should have just 1 command to run to run all tests.
* Devs should be able to run parts of the tests when iterating rapidly on a smaller specific part.

**Comment by peterbe** [comment]
@leplatrem Can you help me understand why my PRs don't trigger a CircleCI PR build?

**Comment by peterbe** [comment]
Also, @leplatrem Perhaps I'm missing something, but why use tox when there's only 1 single environment. Yeah, I know there's a "tox environment" called `flake8` but you can do that manually in Travis or Circle as a one-liner script.

**Comment by peterbe** [comment]
Basically, what I'm pondering is; Can we delete `tox.ini` and `.travis.yml` and just keep the `circle.yml`?

**Comment by leplatrem** [comment]
Yes no problem with getting rid of `tox` and `.travis.yml`.
As for the reason why CircleCI does not trigger your build, I have absolutely no idea. And I don't think I ever entered on the CircleCI UI BTW

**Comment by peterbe** [comment]
@milescrabill Hey, Can you help me out. Why isn't Circle triggering on all PRs?

**Comment by peterbe** [comment]
So once https://github.com/mozilla-services/buildhub/pull/356 lands I'm going to try to get rid of travis and tox and have just 1 cricle yaml config. 

I'll also make it so you can run something like: `make test` to test all the things locally.

**Comment by peterbe** [comment]
One clue is that no Circle here: https://github.com/mozilla-services/buildhub/settings/installations

**Comment by peterbe** [comment]
Interestingly, Tecken runs Circle on every PR but there's not Circle here: https://github.com/mozilla-services/tecken/settings/installations

**Comment by milescrabill** [comment]
Circle is triggered via a webhook [here](https://github.com/mozilla-services/buildhub/settings/hooks/16817138). Are some of the PRs that you're referring to branches on _this_ repo vs. branches from forks?

**Comment by peterbe** [comment]
Chatted to @milescrabill The CircleCI config had preffed off allowing PR builds from forks. He's changed it so now Circle builds PRs from forks [such as mine](https://github.com/mozilla-services/buildhub/pull/358).

**Comment by peterbe** [comment]
https://github.com/mozilla-services/buildhub/pull/358 will remove both tox and travis.

**Comment by peterbe** [comment]
Travis, tox and circle 1.0 is dead! Long live [circle 2.0](https://github.com/mozilla-services/buildhub/blob/master/.circleci/config.yml)!!
