### ISSUE TITLE
Capture and Service Telemetry's Requirements

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#36]
Last month (apr 17) I discussed with @mreid-moz for telemetry requirements. Telemetry's main requirement is being able to cross reference the build id/release channel in a telemetry ping back to a commit in mercurial. 

Summary of requirements: 

- A single source of truth to identify a build. They often get data from non official build and release version of firefox.
- With a build id/release channel be able to look up the commit hash for a release

The [blue print](https://docs.google.com/a/mozilla.com/document/d/1Wa74Ww2lYf29rZlYA1b3oz9yR2IyNQ45DC3svHg1nZs/edit?usp=sharing) contains the detailed meeting notes.

**Comment by mreid-moz** [comment]
See [this conversation](https://github.com/mozilla/telemetry-dashboard/issues/248), for example.

**Comment by mostlygeek** [comment]
That seems essentially the use case you were describing to me. To see a change set between two revisions where all you're starting at is two build id numbers.

**Comment by georgf** [comment]
Here are the needs i ran into from the probe-scraper work:
* list of valid buildids & versions by channel.
* (buildid <-> revision) mapping per channel - need both ways.
* (buildid <-> version) mapping per channel.
* (revision <-> version) mapping per channel, exact.
* (revision -> buildid) mapping per channel, aka: what build is this (revision, channel) tuple in?

I believe this also covers what's needed to make our data jobs aware of past probes (that were removed in trunk/tip already).

**Comment by georgf** [comment]
The change set between revisions should also allow answering the reccuring engineer & analysist question of:
"What build(s) is my patch actually in?"

**Comment by georgf** [comment]
@chutten, @fbertsch, anything else you can think of?

**Comment by chutten** [comment]
day -> current builds at that time. Could be simplified to day -> buildIds

**Comment by mostlygeek** [comment]
@georgf @chutten would a [Web UI](https://mozilla-services.github.io/buildhub/) or an API endpoint be more useful? We're currently working on both.

**Comment by georgf** [comment]
For the Telemetry needs we need this through an API endpoint or as data sets.
E.g. a set of JSON files would be easy to integrate.
That then also allows building webtools on top for other specific use-cases (WhatBuildIsMyPatchIn.com anyone?).

**Comment by georgf** [comment]
Digging in a bit, i see you have data on (deployed?) system addons as well in [the UIs data source](https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/fixtures/records?_sort=-build.date).
That could be useful later for analysis tooling - @mreid-moz ?

**Comment by chutten** [comment]
@mostlygeek ...would there happen to be a timeline for when these requirements might be met? We're trying to schedule work on the tmo frontend and would like to know when to schedule our integration.

**Comment by mostlygeek** [comment]
@chutten there are two main things that have to happen. 

1. Improve the quality of data (#185)
2. Move it pro cloudops' production (#41)

We're in PTO season but I'd be surprised is #185 wasn't closed by mid August. Getting things into production shouldn't hold up your development work. Though you might have to change the DNS name at some point in the future. :) 

Do you have any idea how far back in time you need the data to go? Our goal is total data completeness but we can prioritize cleaning up more recent builds over older ones.

**Comment by chutten** [comment]
The further the better, but generally speaking people are looking for pushlogs in more recent times than for earlier times. So if we have data just from today going forward, I'd still integrate it and put it into production.

**Comment by georgf** [comment]
There is also an email thread on timelines. The email includes the above questions question and more, maybe we can resolve that one first.
