### ISSUE TITLE
Let there be less errors

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub#360]
<img width="1520" alt="screen shot 2018-02-28 at 12 25 59 pm" src="https://user-images.githubusercontent.com/26739/36802426-d3d08cb4-1c82-11e8-95bd-5de66453175f.png">

**Comment by leplatrem** [comment]
See also #333

**Comment by peterbe** [comment]
This issue isn't very good. It's not actionable. Instead we're taking incremental steps like: https://github.com/mozilla-services/buildhub/pull/389/files
