### ISSUE TITLE
Change license to MPL 2.0

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub#366]
We're currently using Apache License 2.0. We [should be using MPL 2](https://github.com/mozilla/product-delivery/blob/master/STANDARDS.md#repositories)

**Comment by peterbe** [comment]
@leplatrem Do you know why it's Apache 2.0? And would it be hellish to change it now?

**Comment by mostlygeek** [comment]
Change it to MPL2.  Pretty sure it won't affect anybody.

**Comment by leplatrem** [comment]
There was something annoying with MPL2 like having a header in every source file or something like that. Apache 2 was cool enough, never bothered

**Comment by peterbe** [comment]
That's not hard to add. I'll change it to MPL 2.

**Comment by leplatrem** [comment]
> That's not hard to add

The headers? In each file, present and future? That's enough to avoid using a license IMO :)

**Comment by peterbe** [comment]
Yeah, it sucks but we've said we'll use MPL2. [78 files](https://github.com/mozilla-services/tecken/search?utf8=%E2%9C%93&q=This+Source+Code+Form+is+subject+to+the+terms+of+the+Mozilla+Public&type=) :)

**Comment by leplatrem** [comment]
Next step, add this to every file:
```
# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
```
