### ISSUE TITLE
Question: how to query for the latest official Firefox version?

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/buildhub#385]
I'm trying to make a query for the latest official Firefox version on release. I've come up with [this query](https://buildhub.prod.mozaws.net/v1/buckets/build-hub/collections/releases/records?target.channel=release&target.locale=en-US&target.os=win&_limit=1&_sort=-build.id&_fields=target.version).

Right now it returns the following:
```json
{
  "data": [
    {
      "target": {
        "version": "59.0.2rc1"
      },
      "id": "firefox_59-0-2rc1_win32_en-us",
      "last_modified": 1522088024832
    }
  ]
}
```

Is there a way to exclude "rc" builds? What is the recommended way to get the latest official version?

**Comment by leplatrem** [comment]
That's a really good point, there doesn't seem to be any attribute to distinguish latest official from a release candidate!

I was trying to come up with an ElasticSearch query to exclude the `rc` versions. Check if it works, it looks like so:

```
echo '{
  "query": {
    "bool": {
      "must_not": {
        "regexp": {
          "target.version": ".*rc.*"
        }
      },
      "filter": [{
        "term": {
          "target.channel": "release"
        }
      }, {
        "term": {
          "target.locale": "en-US"
        }
      }, {
        "term": {
          "source.product": "firefox"
        }
      }, {
        "term": {
          "target.os": "win"
        }
      }]
    }
  },
  "sort" : [{
    "build.id": "desc"
  }],
  "size": 1
}' | http POST https://buildhub.prod.mozaws.net/v1/buckets/build-hub/collections/releases/search
```
(I used httpie.org but you can use curl of course)

**Comment by leplatrem** [comment]
Also, if you use `jq`, you can get the `target.version` by piping the previous command to `|  jq -r '.hits.hits[0]._source.target.version'`
