### ISSUE TITLE
Migrate MozillaPulse client to Python 3

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#39]
If we want to leverage what we receive in Pulse, we'll have to migrate it to Python 3

Rework first version of patch here: https://bugzilla.mozilla.org/show_bug.cgi?id=1294230

**Comment by mostlygeek** [comment]
A bigger question: should we standardize on Python3? In #41 I want to deploy aggregator code in a docker container. We'll need to pick a python base container.

**Comment by Natim** [comment]
We are relying for the scrapping scripts on asyncio which is a event loop API that was brought to Python 3 so yes, we should :)

**Comment by leplatrem** [comment]
> A bigger question: should we standardize on Python3?

Yes. Standardizing on Python2 would be like targetting Windows XP

**Comment by leplatrem** [comment]
Port of MozillaPulse to Python3 was merged. Waiting for release on Pypi.

**Comment by leplatrem** [comment]
Was moved to Github https://github.com/mozilla-services/mozillapulse
And version 1.3 was released with Py3 support :)
