### ISSUE TITLE
Infer channel information?

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#4]
Of the 1082 records at the time of this writing, there's exactly 0 with a specified "channel" field. Either it's not an information we get back from pulse on the messages we're interested in, either there's an issue when storing those in kinto?

**Comment by magopian** [comment]
This is not an issue anymore (check the latest scraping dump at https://drive.google.com/a/mozilla.com/file/d/0BwqPWo33VPF3cDdUTGVkTDZNZk0/view?usp=drive_web)

**Comment by leplatrem** [comment]
The records who don't have build information (old releases) also don't have `channel` infos.

Maybe we should infer channel from version? (`if "b" in version then "beta"` ?)

**Comment by Natim** [comment]
I find it possible to infer it from the URL for instance.

**Comment by leplatrem** [comment]
Closed by #52
