### ISSUE TITLE
Operational Spec for BuildHub Version 1.0

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#41]
This issue is to discuss how we want to structure the project to make it easy to configure and deploy for the operations team. Currently there are are server side and client side components. The server side components are daemons and cron job compatible scrapers. The client side is a static HTML website. 

Data is stored in a kinto instance which is backed by Postgresql RDS. This is relatively slow moving and shouldn't require much operational work other than standing it up and keeping it updated. 

Server side code
============

* ship a container with all server based code
* follow [dockerflow](https://github.com/mozilla-services/dockerflow)
* Build/test container in circle.ci
* Publish container to hub.docker.com/mozilla/buildhub
* A single container with all of the scripts / workers / scrapers / etc
* version.json written into the container, accessible by `run.sh version` 
* a `run.sh` file as the container's `ENTRYPOINT`. 

run.sh
-------------
Buildhub's docker container is a toolbox and `run.sh` provides an abstraction to the tools inside.  Here are an examples of how `run.sh` works as the `ENTRYPOINT`:

````
Self documenting...
$ docker run buildhub:master help


On the CLI or as cronjob: 
$ docker run buildhub:master scrape_archives --auth user:password


As a daemon: 
$ docker run --envfile /etc/dockerflow/buildhub-pulse.txt \
    buildhub:master pulse_listener
````

Web UI
=====
The WebUI (SearchKit: #127) also needs to be deployed. 

- Hosted in S3 fronted by Cloudfront. On the https://buildhub.services.mozilla.com domain? 
- Automatic deployment from Circle => Stage|Prod would be nice to have

**Comment by mostlygeek** [comment]
See this deployment bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1380695

**Comment by leplatrem** [comment]
Since the server side is already shipped as a Docker container, the jobs in a Lambda archive, and the UI deployed on Github (modulo #234), should we consider this done?

**Comment by leplatrem** [comment]
Well, since the ``latest-inventory-to-kinto` takes more than 5min, we can't run it from a Lambda.
I'll give a shot to this.
