### ISSUE TITLE
Generating existing from scratch is expensive

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub#446]
Suppose you delete the `.records-hashes-$SERVER_NAME.json` file. That means this code right here: https://github.com/mozilla-services/buildhub/blob/ee484fab5ac852036b355da0d8be1910955ee3b9/jobs/buildhub/to_kinto.py#L158-L161 is going to extract every single record from the Kinto database into a monster list of dicts. 

I measured it, with `memory_profiler` in my docker with a postgres database of about 500,000 records. Generating that `new_records` dict eats up about 1700MB.
See https://irccloud.mozilla.com/pastebin/ZhAoBDia/

The solution has to be to consume that paginated result as a stream and for each patch of 10,000 records make the hashes and then reuse that allocated memory for the next 10,000 records. 

@leplatrem I don't see a whole lot in [the documentation](https://github.com/Kinto/kinto-http.py#pagination) about to do the pagination i any other way. Do you have some ideas?

**Comment by bqbn** [comment]
Did some manual runs on -stage using v1.2.1, and it shows that the program requires at least 5 GB memory in order to finish, or it gets OOM killed.

Without this being fixed, we can expect that the program will need more memory due to the ever increasing database.

**Comment by leplatrem** [comment]
> @leplatrem I don't see a whole lot in the documentation about to do the pagination i any other way. Do you have some ideas?

Indeed, the pagination is not exposed in the kinto-http client :(

As a work around, using raw requests is relatively easy (*untested*):

```py

url = records_url
while True:
   resp = requests.get(url, params={"_since": timestamp, "_limit": 1000})
   page_records = resp.json["data"]
   # ... process(page_records)
   url = resp.headers.get("Next-Page")
   if url is None:
       break

```

**Comment by peterbe** [comment]
Fixed by https://github.com/mozilla-services/buildhub/commit/71f34fd67635c9bde3e6b6e5668a34838c4f6fe2
