### ISSUE TITLE
Add target_os, target_cpu, target_vendor info, target_alias in the build info

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#54]
https://archive.mozilla.org/pub/thunderbird/candidates/52.0.1-candidates/build3/linux-x86_64/en-US/thunderbird-52.0.1.json

**Comment by leplatrem** [comment]
Are we sure want to stick all this in every record?

**Comment by Natim** [comment]
After discussion with @mostlygeek it seemed that if this information are there maybe someone will need them at some point and it doesn't cost a lot to store them over while scrapping.

It is up to you, I am fine with both outcomes.
