### ISSUE TITLE
Remove the *Filter fields from the model

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#65]
Once #40 is landed, we'll have a `Route` stored in the model, which holds all the information for the filters, thus making the individual `*Filter` fields redundant.

**Comment by n1k0** [comment]
> we'll have a Route stored in the model, which holds all the information for the filters, thus making the individual *Filter fields redundant.

But we still have to store selected filters somewhere before sending the form, right? I can't really see us storing a *temporary route* every time users tweak a filter, then actually load that route when they press the submit button. Sure, that might be technically feasible, but slightly overkill I think.

But maybe you has something else in mind?

**Comment by magopian** [comment]
This issue was relevant when changing a filter changed the route (and the results) dynamically. I don't think it's relevant anymore now that we have a form. Closing, will reopen in the future if we get back to something more dynamic.
