### ISSUE TITLE
What are partners releases?

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#81]
```
$ tree -L 2 pub/firefox/releases/partners
├── fujitsu-siemens
│   ├── 2.0.0.6
├── google
│   ├── 1.5.0.12
│   ├── 2.0.0.6
├── packardbell
│   ├── 2.0.0.6
├── seznam
│   ├── 2.0.0.6
├── yahoo
│   ├── 1.5.0.6
│   ├── 1.5.0.7
└── yahoo-japan
    ├── 2.0.0.6

```

Should we handle them or just ignore them?

**Comment by mostlygeek** [comment]
We create custom FF builds for partners. However, the builds available on archive.mozilla.org are really out of date. Looks like they are from around 2015. We **should not** index these. 

The new partner builds are in a private S3 bucket. The only way to list/index them is with custom AWS credentials. We may want to index these. I'll talk to @mkaply about this. I don't think it's necessary for V1.

**Comment by mostlygeek** [comment]
talked to @mkaply. We don't need to index partner builds.

Notes: 
- partner builds are essentially: standard build but we "add a distribution directory that contains possibly extensions, search engines and some prefs. But it's a standard build repackaged and resigned". 
- the build id is not changed for partner builds
- the release channel is not custom
- some partner builds are copied over to pub/firefox/candidates/53.0.2-candidates/build1/partner-repacks/ ... but we can skip these. 

So for now we can skip indexing of partner builds.
