### ISSUE TITLE
Version filter sometimes results in a 503

### ISSUE THREAD

**Issue by magopian** [mozilla-services/buildhub#86]
Trying to filter on certain version numbers results in the following error message in the console:
```
An error occured while fetching the build records: KintoError 503 "Service Unavailable" { errno = 201, message = "Service temporary unavailable due to overloading or maintenance, please retry later.", code = 503, error = "Service Unavailable" }
```

The request sent to Kinto is: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=10&_sort=-build.date&target.version=0.8

If however you filter on version `53.0b1` there's no problem: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=10&_sort=-build.date&target.version=53.0b1

**Comment by Natim** [comment]
Yes it is a known bug, this https://github.com/Kinto/kinto/issues/1217

To fix your issue right now, please add quotes around in the querystring. However we need to fix this.
