### ISSUE TITLE
[ui] Add a page with code snippets

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#9]
In order to show the possibility of the underlying APIs, we could have a static page that:

* Shows a curl example to retrieve the revision of a buildid (for example)
* Shows kinto-http.(py|js) snippets to query the API (simple stuff like list of locales for a version) 
* Links to Kinto API docs
* Info to contact us (IRC, 

Thoughts?

**Comment by n1k0** [comment]
Great idea!

**Comment by glasserc** [comment]
Oops never mind
