### ISSUE TITLE
Total records value displayed incorrectly on FF Nightly

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#98]
![number-of-builds](https://cloud.githubusercontent.com/assets/229453/26776548/d471e37e-49d9-11e7-94cc-97e475299ef1.png)

As you can see it says, *10 build displayed (0 total)*

**Comment by n1k0** [comment]
Looks like a header parsing issue. I know there's a difference in the way Firefox and Chrome exposes them, like Chrome always lowercase them and Firefox doesn't (or the other way around).

Maybe we should update elm-kinto to always rely on a lower-cased version.

**Comment by n1k0** [comment]
Hmm nope, elm-kinto expects case to be preserved https://github.com/Kinto/elm-kinto/blob/master/src/Kinto.elm#L320-L322

And Firefox doesn't lower case that header name:

![](http://i.imgur.com/pnitRY1.png)

**Comment by Natim** [comment]
Can we force to handle all headers in a case insensitive maner?

**Comment by n1k0** [comment]
In this case that's not the root issue.

**Comment by Natim** [comment]
No but it feels important that it doesn't become one in the future :)

**Comment by n1k0** [comment]
Please provide a patch to elm-kinto then. But here it's not related to this issue.

Also, it's super odd that it only breaks for Nightly. Firefox stable is fine. I can't see any difference in the way responses are exposed in the devtools.

**Comment by mostlygeek** [comment]
This bug also affects pagination in nightly. There's no button to load more records at the bottom.

**Comment by magopian** [comment]
Some investigation: tried `Debug.log`ing the headers that the elm http library passes to elm-kinto on ff release (53) and nightly (55).

Nightly:
```
Dict.fromList [("cache-control","no-cache, no-store"),("content-length","44837"),("content-type","application/json"),("etag","\"1496397843245\""),("last-modified","Fri, 02 Jun 2017 10:04:03 GMT"),("next-page","https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tOTZhMjJiZjQtY2E5Yi00Yjg3LWI5NDItODU0MGE5YzViZmFhIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5NzgxNTE3Mn0sIm9mZnNldCI6MTAwfQ%3D%3D&_sort=-build.date&_limit=100"),("total-records","36452")]
```

**Comment by magopian** [comment]
Some investigation: tried `Debug.log`ing the headers that the elm http library passes to elm-kinto on ff release (53) and nightly (55).

Nightly:
```
Dict.fromList [("cache-control","no-cache, no-store"),("content-length","44837"),("content-type","application/json"),("etag","\"1496397843245\""),("last-modified","Fri, 02 Jun 2017 10:04:03 GMT"),("next-page","https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tOTZhMjJiZjQtY2E5Yi00Yjg3LWI5NDItODU0MGE5YzViZmFhIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5NzgxNTE3Mn0sIm9mZnNldCI6MTAwfQ%3D%3D&_sort=-build.date&_limit=100"),("total-records","36452")]
```

Release:
```
Dict.fromList [("Cache-Control","no-cache, no-store"),("Content-Length","44837"),("Content-Type","application/json"),("Etag","\"1496397843245\""),("Last-Modified","Fri, 02 Jun 2017 10:04:03 GMT"),("Next-Page","https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tODM2YTdkOTQtYjYxMy00MjJhLTg4MDItNmQyOWQ2MDcxNDNmIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5NzgxNTE3Mn0sIm9mZnNldCI6MTAwfQ%3D%3D&_sort=-build.date&_limit=100"),("Total-Records","36452")]
```

So it's pretty obvious that for some reason, nightly is lower-casing the header names. Maybe we should make `elm-kinto` not care about the casing?

Any thoughts @n1k0 ?

**Comment by n1k0** [comment]
Nice investigation thanks. So we need to lower case all headers before checking them. That means bumping a new major version of elm-kinto :/

**Comment by n1k0** [comment]
Wait, not a major, just a patch release, that's internal stuff.

**Comment by n1k0** [comment]
As to why are they doing that, I know Chrome did the same at some point. The funny thing is they don't seem be doing that anymore, but now Nightly does. Anyway, lower-casing headers seems the safe, future-proof option here.

**Comment by Natim** [comment]
Refs https://github.com/Kinto/elm-kinto/pull/30

**Comment by Natim** [comment]
Fixed and deployed. https://mozilla-services.github.io/buildhub/

**Comment by mostlygeek** [comment]
Confirmed that it is nightly and not Elm. 

Using this in the webconsole: 

```js
var request = new XMLHttpRequest();
request.open("GET", "https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=100&_sort=-build.date", true);
request.send();
request.onreadystatechange = function() {
  if(this.readyState == this.HEADERS_RECEIVED) {
    console.log(request.getAllResponseHeaders());
  }
}
```

Nightly: 

```
cache-control: no-cache, no-store
content-length: 44837
content-type: application/json
etag: "1496397843245"
last-modified: Fri, 02 Jun 2017 10:04:03 GMT
next-page: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tMjY5ZTgzMzYtMWVhZC00ODBkLTlhNzYtNjgzYjA4MDg3ZjdlIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5NzgxNTE3Mn0sIm9mZnNldCI6MTAwfQ%3D%3D&_sort=-build.date&_limit=100
total-records: 36452
```

Dev edition: 

```
Cache-Control: no-cache, no-store
Content-Type: application/json
Etag: "1496397843245"
Last-Modified: Fri, 02 Jun 2017 10:04:03 GMT
Next-Page: https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_token=eyJub25jZSI6InBhZ2luYXRpb24tdG9rZW4tODMyM2MyMTQtZjg0ZC00MDRiLThmNGItMGI5NWI5Yjc4MmQyIiwibGFzdF9yZWNvcmQiOnsibGFzdF9tb2RpZmllZCI6MTQ5NjM5NzgxNTE3Mn0sIm9mZnNldCI6MTAwfQ%3D%3D&_sort=-build.date&_limit=100
Total-Records: 36452
Content-Length: 44837
```

Seems like a pretty bad regression that would break things all over the place. I'll file a bug for it...

**Comment by mostlygeek** [comment]
Ahh found [Bug 1370485](https://bugzilla.mozilla.org/show_bug.cgi?id=1370485). In nightly the pref `dom.xhr.lowercase_header.enabled` has been flipped to `true`. 

I'll comment there that we hit this bug.
